// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Statement struct {
	ID           uuid.UUID      `json:"id"`
	CardID       uuid.UUID      `json:"card_id"`
	Year         int32          `json:"year"`
	Month        int32          `json:"month"`
	StatementBal sql.NullString `json:"statement_bal"`
	FilePath     sql.NullString `json:"file_path"`
	ParsedAt     sql.NullTime   `json:"parsed_at"`
	CreatedAt    time.Time      `json:"created_at"`
}
