// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CardStatement struct {
	ID           uuid.UUID      `json:"id"`
	StatementID  uuid.UUID      `json:"statement_id"`
	CardLast4    string         `json:"card_last4"`
	CardID       uuid.NullUUID  `json:"card_id"`
	Status       int16          `json:"status"`
	StatementBal sql.NullString `json:"statement_bal"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Statement struct {
	ID           uuid.UUID      `json:"id"`
	Year         sql.NullInt32  `json:"year"`
	Month        sql.NullInt32  `json:"month"`
	StatementBal sql.NullString `json:"statement_bal"`
	FilePath     sql.NullString `json:"file_path"`
	Status       int16          `json:"status"`
	Message      sql.NullString `json:"message"`
	FileHash     sql.NullString `json:"file_hash"`
	ParsedAt     sql.NullTime   `json:"parsed_at"`
	CreatedAt    time.Time      `json:"created_at"`
}
