// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cardStatementExistsForPeriod = `-- name: CardStatementExistsForPeriod :one
SELECT EXISTS(
    SELECT 1
    FROM card_statement cs
    JOIN statements s ON s.id = cs.statement_id
    WHERE cs.card_id = $1
      AND s.year     = $2
      AND s.month    = $3
      AND cs.status  = 1
)
`

type CardStatementExistsForPeriodParams struct {
	CardID uuid.NullUUID `json:"card_id"`
	Year   sql.NullInt32 `json:"year"`
	Month  sql.NullInt32 `json:"month"`
}

func (q *Queries) CardStatementExistsForPeriod(ctx context.Context, arg CardStatementExistsForPeriodParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, cardStatementExistsForPeriod, arg.CardID, arg.Year, arg.Month)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getStatementByID = `-- name: GetStatementByID :one
SELECT id, year, month, statement_bal, file_path, status, message, file_hash, parsed_at, created_at
FROM statements
WHERE id = $1
`

func (q *Queries) GetStatementByID(ctx context.Context, id uuid.UUID) (Statement, error) {
	row := q.db.QueryRowContext(ctx, getStatementByID, id)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.Status,
		&i.Message,
		&i.FileHash,
		&i.ParsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCardStatement = `-- name: InsertCardStatement :one
INSERT INTO card_statement (statement_id, card_last4, card_id, status, statement_bal)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, statement_id, card_last4, card_id, status, statement_bal, created_at
`

type InsertCardStatementParams struct {
	StatementID  uuid.UUID      `json:"statement_id"`
	CardLast4    string         `json:"card_last4"`
	CardID       uuid.NullUUID  `json:"card_id"`
	Status       int16          `json:"status"`
	StatementBal sql.NullString `json:"statement_bal"`
}

func (q *Queries) InsertCardStatement(ctx context.Context, arg InsertCardStatementParams) (CardStatement, error) {
	row := q.db.QueryRowContext(ctx, insertCardStatement,
		arg.StatementID,
		arg.CardLast4,
		arg.CardID,
		arg.Status,
		arg.StatementBal,
	)
	var i CardStatement
	err := row.Scan(
		&i.ID,
		&i.StatementID,
		&i.CardLast4,
		&i.CardID,
		&i.Status,
		&i.StatementBal,
		&i.CreatedAt,
	)
	return i, err
}

const insertStatement = `-- name: InsertStatement :one
INSERT INTO statements (file_hash, file_path, status)
VALUES ($1, $2, 0)
RETURNING id, year, month, statement_bal, file_path, status, message, file_hash, parsed_at, created_at
`

type InsertStatementParams struct {
	FileHash sql.NullString `json:"file_hash"`
	FilePath sql.NullString `json:"file_path"`
}

func (q *Queries) InsertStatement(ctx context.Context, arg InsertStatementParams) (Statement, error) {
	row := q.db.QueryRowContext(ctx, insertStatement, arg.FileHash, arg.FilePath)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.Status,
		&i.Message,
		&i.FileHash,
		&i.ParsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const queryStatementsByCard = `-- name: QueryStatementsByCard :many
SELECT s.id, s.year, s.month, s.statement_bal, s.file_path, s.status, s.message, s.file_hash, s.parsed_at, s.created_at
FROM statements s
JOIN card_statement cs ON cs.statement_id = s.id
WHERE cs.card_id = $1
ORDER BY s.created_at DESC
`

func (q *Queries) QueryStatementsByCard(ctx context.Context, cardID uuid.NullUUID) ([]Statement, error) {
	rows, err := q.db.QueryContext(ctx, queryStatementsByCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Statement
	for rows.Next() {
		var i Statement
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Month,
			&i.StatementBal,
			&i.FilePath,
			&i.Status,
			&i.Message,
			&i.FileHash,
			&i.ParsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statementFullyParsedByHash = `-- name: StatementFullyParsedByHash :one
SELECT EXISTS(
    SELECT 1 FROM statements s
    WHERE s.file_hash = $1
      AND s.status = 1
      AND NOT EXISTS (
          SELECT 1 FROM card_statement cs
          WHERE cs.statement_id = s.id AND cs.status = 2
      )
)
`

// Reject only when the statement is fully parsed (no skipped card_statements).
func (q *Queries) StatementFullyParsedByHash(ctx context.Context, fileHash sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, statementFullyParsedByHash, fileHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateStatementBalance = `-- name: UpdateStatementBalance :one
UPDATE statements
SET statement_bal = $2,
    parsed_at     = NOW()
WHERE id = $1
RETURNING id, year, month, statement_bal, file_path, status, message, file_hash, parsed_at, created_at
`

type UpdateStatementBalanceParams struct {
	ID           uuid.UUID      `json:"id"`
	StatementBal sql.NullString `json:"statement_bal"`
}

func (q *Queries) UpdateStatementBalance(ctx context.Context, arg UpdateStatementBalanceParams) (Statement, error) {
	row := q.db.QueryRowContext(ctx, updateStatementBalance, arg.ID, arg.StatementBal)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.Status,
		&i.Message,
		&i.FileHash,
		&i.ParsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateStatementError = `-- name: UpdateStatementError :one
UPDATE statements
SET status  = 2,
    message = $2
WHERE id = $1
RETURNING id, year, month, statement_bal, file_path, status, message, file_hash, parsed_at, created_at
`

type UpdateStatementErrorParams struct {
	ID      uuid.UUID      `json:"id"`
	Message sql.NullString `json:"message"`
}

func (q *Queries) UpdateStatementError(ctx context.Context, arg UpdateStatementErrorParams) (Statement, error) {
	row := q.db.QueryRowContext(ctx, updateStatementError, arg.ID, arg.Message)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.Status,
		&i.Message,
		&i.FileHash,
		&i.ParsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateStatementParsed = `-- name: UpdateStatementParsed :one
UPDATE statements
SET year          = $2,
    month         = $3,
    statement_bal = $4,
    status        = 1,
    parsed_at     = NOW()
WHERE id = $1
RETURNING id, year, month, statement_bal, file_path, status, message, file_hash, parsed_at, created_at
`

type UpdateStatementParsedParams struct {
	ID           uuid.UUID      `json:"id"`
	Year         sql.NullInt32  `json:"year"`
	Month        sql.NullInt32  `json:"month"`
	StatementBal sql.NullString `json:"statement_bal"`
}

func (q *Queries) UpdateStatementParsed(ctx context.Context, arg UpdateStatementParsedParams) (Statement, error) {
	row := q.db.QueryRowContext(ctx, updateStatementParsed,
		arg.ID,
		arg.Year,
		arg.Month,
		arg.StatementBal,
	)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.Status,
		&i.Message,
		&i.FileHash,
		&i.ParsedAt,
		&i.CreatedAt,
	)
	return i, err
}
