// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getStatementByID = `-- name: GetStatementByID :one
SELECT id, card_id, year, month, statement_bal, file_path, parsed_at, created_at, status, message, file_hash
FROM statements
WHERE id = $1
`

func (q *Queries) GetStatementByID(ctx context.Context, id uuid.UUID) (Statement, error) {
	row := q.db.QueryRowContext(ctx, getStatementByID, id)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.ParsedAt,
		&i.CreatedAt,
		&i.Status,
		&i.Message,
		&i.FileHash,
	)
	return i, err
}

const insertStatement = `-- name: InsertStatement :one
INSERT INTO statements (card_id, file_hash, file_path, status)
VALUES ($1, $2, $3, 0)
RETURNING id, card_id, year, month, statement_bal, file_path, parsed_at, created_at, status, message, file_hash
`

type InsertStatementParams struct {
	CardID   uuid.UUID      `json:"card_id"`
	FileHash sql.NullString `json:"file_hash"`
	FilePath sql.NullString `json:"file_path"`
}

func (q *Queries) InsertStatement(ctx context.Context, arg InsertStatementParams) (Statement, error) {
	row := q.db.QueryRowContext(ctx, insertStatement, arg.CardID, arg.FileHash, arg.FilePath)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.ParsedAt,
		&i.CreatedAt,
		&i.Status,
		&i.Message,
		&i.FileHash,
	)
	return i, err
}

const queryStatementsByCard = `-- name: QueryStatementsByCard :many
SELECT id, card_id, year, month, statement_bal, file_path, parsed_at, created_at, status, message, file_hash
FROM statements
WHERE card_id = $1
ORDER BY created_at DESC
`

func (q *Queries) QueryStatementsByCard(ctx context.Context, cardID uuid.UUID) ([]Statement, error) {
	rows, err := q.db.QueryContext(ctx, queryStatementsByCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Statement
	for rows.Next() {
		var i Statement
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Year,
			&i.Month,
			&i.StatementBal,
			&i.FilePath,
			&i.ParsedAt,
			&i.CreatedAt,
			&i.Status,
			&i.Message,
			&i.FileHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statementExistsByCardPeriod = `-- name: StatementExistsByCardPeriod :one
SELECT EXISTS(
    SELECT 1 FROM statements
    WHERE card_id = $1
      AND year    = $2
      AND month   = $3
      AND status != 2
)
`

type StatementExistsByCardPeriodParams struct {
	CardID uuid.UUID     `json:"card_id"`
	Year   sql.NullInt32 `json:"year"`
	Month  sql.NullInt32 `json:"month"`
}

func (q *Queries) StatementExistsByCardPeriod(ctx context.Context, arg StatementExistsByCardPeriodParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, statementExistsByCardPeriod, arg.CardID, arg.Year, arg.Month)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const statementExistsByHash = `-- name: StatementExistsByHash :one
SELECT EXISTS(SELECT 1 FROM statements WHERE file_hash = $1 AND status = 1)
`

func (q *Queries) StatementExistsByHash(ctx context.Context, fileHash sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, statementExistsByHash, fileHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateStatementBalance = `-- name: UpdateStatementBalance :one
UPDATE statements
SET statement_bal = $2,
    parsed_at     = NOW()
WHERE id = $1
RETURNING id, card_id, year, month, statement_bal, file_path, parsed_at, created_at, status, message, file_hash
`

type UpdateStatementBalanceParams struct {
	ID           uuid.UUID      `json:"id"`
	StatementBal sql.NullString `json:"statement_bal"`
}

func (q *Queries) UpdateStatementBalance(ctx context.Context, arg UpdateStatementBalanceParams) (Statement, error) {
	row := q.db.QueryRowContext(ctx, updateStatementBalance, arg.ID, arg.StatementBal)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.ParsedAt,
		&i.CreatedAt,
		&i.Status,
		&i.Message,
		&i.FileHash,
	)
	return i, err
}

const updateStatementError = `-- name: UpdateStatementError :one
UPDATE statements
SET status  = 2,
    message = $2
WHERE id = $1
RETURNING id, card_id, year, month, statement_bal, file_path, parsed_at, created_at, status, message, file_hash
`

type UpdateStatementErrorParams struct {
	ID      uuid.UUID      `json:"id"`
	Message sql.NullString `json:"message"`
}

func (q *Queries) UpdateStatementError(ctx context.Context, arg UpdateStatementErrorParams) (Statement, error) {
	row := q.db.QueryRowContext(ctx, updateStatementError, arg.ID, arg.Message)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.ParsedAt,
		&i.CreatedAt,
		&i.Status,
		&i.Message,
		&i.FileHash,
	)
	return i, err
}

const updateStatementParsed = `-- name: UpdateStatementParsed :one
UPDATE statements
SET year          = $2,
    month         = $3,
    statement_bal = $4,
    status        = 1,
    parsed_at     = NOW()
WHERE id = $1
RETURNING id, card_id, year, month, statement_bal, file_path, parsed_at, created_at, status, message, file_hash
`

type UpdateStatementParsedParams struct {
	ID           uuid.UUID      `json:"id"`
	Year         sql.NullInt32  `json:"year"`
	Month        sql.NullInt32  `json:"month"`
	StatementBal sql.NullString `json:"statement_bal"`
}

func (q *Queries) UpdateStatementParsed(ctx context.Context, arg UpdateStatementParsedParams) (Statement, error) {
	row := q.db.QueryRowContext(ctx, updateStatementParsed,
		arg.ID,
		arg.Year,
		arg.Month,
		arg.StatementBal,
	)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.ParsedAt,
		&i.CreatedAt,
		&i.Status,
		&i.Message,
		&i.FileHash,
	)
	return i, err
}
