// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getStatementByID = `-- name: GetStatementByID :one
SELECT id, card_id, year, month, statement_bal, file_path, parsed_at, created_at
FROM statements
WHERE id = $1
`

func (q *Queries) GetStatementByID(ctx context.Context, id uuid.UUID) (Statement, error) {
	row := q.db.QueryRowContext(ctx, getStatementByID, id)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.ParsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertStatement = `-- name: InsertStatement :one
INSERT INTO statements (card_id, year, month, file_path)
VALUES ($1, $2, $3, $4)
RETURNING id, card_id, year, month, statement_bal, file_path, parsed_at, created_at
`

type InsertStatementParams struct {
	CardID   uuid.UUID      `json:"card_id"`
	Year     int32          `json:"year"`
	Month    int32          `json:"month"`
	FilePath sql.NullString `json:"file_path"`
}

func (q *Queries) InsertStatement(ctx context.Context, arg InsertStatementParams) (Statement, error) {
	row := q.db.QueryRowContext(ctx, insertStatement,
		arg.CardID,
		arg.Year,
		arg.Month,
		arg.FilePath,
	)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.ParsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const queryStatementsByCard = `-- name: QueryStatementsByCard :many
SELECT id, card_id, year, month, statement_bal, file_path, parsed_at, created_at
FROM statements
WHERE card_id = $1
ORDER BY year DESC, month DESC
`

func (q *Queries) QueryStatementsByCard(ctx context.Context, cardID uuid.UUID) ([]Statement, error) {
	rows, err := q.db.QueryContext(ctx, queryStatementsByCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Statement
	for rows.Next() {
		var i Statement
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Year,
			&i.Month,
			&i.StatementBal,
			&i.FilePath,
			&i.ParsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatementBalance = `-- name: UpdateStatementBalance :one
UPDATE statements
SET statement_bal = $2, parsed_at = NOW()
WHERE id = $1
RETURNING id, card_id, year, month, statement_bal, file_path, parsed_at, created_at
`

type UpdateStatementBalanceParams struct {
	ID           uuid.UUID      `json:"id"`
	StatementBal sql.NullString `json:"statement_bal"`
}

func (q *Queries) UpdateStatementBalance(ctx context.Context, arg UpdateStatementBalanceParams) (Statement, error) {
	row := q.db.QueryRowContext(ctx, updateStatementBalance, arg.ID, arg.StatementBal)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Year,
		&i.Month,
		&i.StatementBal,
		&i.FilePath,
		&i.ParsedAt,
		&i.CreatedAt,
	)
	return i, err
}
