ALTER TABLE statements ALTER COLUMN year  DROP NOT NULL;
ALTER TABLE statements ALTER COLUMN month DROP NOT NULL;

ALTER TABLE statements ADD COLUMN status   SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE statements ADD COLUMN message  TEXT;
ALTER TABLE statements ADD COLUMN file_hash TEXT;
