// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type CategoryMapping struct {
	ID              uuid.UUID `json:"id"`
	MerchantPattern string    `json:"merchant_pattern"`
	CategoryID      uuid.UUID `json:"category_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type Transaction struct {
	ID          uuid.UUID `json:"id"`
	StatementID uuid.UUID `json:"statement_id"`
	CardID      uuid.UUID `json:"card_id"`
	TxnDate     time.Time `json:"txn_date"`
	MerchantRaw string    `json:"merchant_raw"`
	Merchant    string    `json:"merchant"`
	Amount      string    `json:"amount"`
	CategoryID  uuid.UUID `json:"category_id"`
	CreatedAt   time.Time `json:"created_at"`
}
