// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteCategoryMapping = `-- name: DeleteCategoryMapping :exec
DELETE FROM category_mapping WHERE id = $1
`

func (q *Queries) DeleteCategoryMapping(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryMapping, id)
	return err
}

const deleteTransactionsByStatement = `-- name: DeleteTransactionsByStatement :exec
DELETE FROM transactions WHERE statement_id = $1
`

func (q *Queries) DeleteTransactionsByStatement(ctx context.Context, statementID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionsByStatement, statementID)
	return err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, created_at FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.statement_id, t.card_id, t.txn_date, t.merchant_raw, t.merchant, t.amount,
       c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
       t.created_at
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.id = $1
`

type GetTransactionByIDRow struct {
	ID           uuid.UUID `json:"id"`
	StatementID  uuid.UUID `json:"statement_id"`
	CardID       uuid.UUID `json:"card_id"`
	TxnDate      time.Time `json:"txn_date"`
	MerchantRaw  string    `json:"merchant_raw"`
	Merchant     string    `json:"merchant"`
	Amount       string    `json:"amount"`
	CategoryID   uuid.UUID `json:"category_id"`
	CategoryName string    `json:"category_name"`
	CategorySlug string    `json:"category_slug"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (GetTransactionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.StatementID,
		&i.CardID,
		&i.TxnDate,
		&i.MerchantRaw,
		&i.Merchant,
		&i.Amount,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.CreatedAt,
	)
	return i, err
}

const insertCategoryMapping = `-- name: InsertCategoryMapping :one
INSERT INTO category_mapping (merchant_pattern, category_id)
VALUES ($1, (SELECT id FROM categories WHERE slug = $2))
RETURNING id, merchant_pattern, category_id, created_at
`

type InsertCategoryMappingParams struct {
	MerchantPattern string `json:"merchant_pattern"`
	Slug            string `json:"slug"`
}

func (q *Queries) InsertCategoryMapping(ctx context.Context, arg InsertCategoryMappingParams) (CategoryMapping, error) {
	row := q.db.QueryRowContext(ctx, insertCategoryMapping, arg.MerchantPattern, arg.Slug)
	var i CategoryMapping
	err := row.Scan(
		&i.ID,
		&i.MerchantPattern,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (statement_id, card_id, txn_date, merchant_raw, merchant, amount, category_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, statement_id, card_id, txn_date, merchant_raw, merchant, amount, category_id, created_at
`

type InsertTransactionParams struct {
	StatementID uuid.UUID `json:"statement_id"`
	CardID      uuid.UUID `json:"card_id"`
	TxnDate     time.Time `json:"txn_date"`
	MerchantRaw string    `json:"merchant_raw"`
	Merchant    string    `json:"merchant"`
	Amount      string    `json:"amount"`
	CategoryID  uuid.UUID `json:"category_id"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, insertTransaction,
		arg.StatementID,
		arg.CardID,
		arg.TxnDate,
		arg.MerchantRaw,
		arg.Merchant,
		arg.Amount,
		arg.CategoryID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StatementID,
		&i.CardID,
		&i.TxnDate,
		&i.MerchantRaw,
		&i.Merchant,
		&i.Amount,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const queryCategories = `-- name: QueryCategories :many
SELECT id, name, slug, created_at FROM categories ORDER BY name
`

func (q *Queries) QueryCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, queryCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryCategoryMappings = `-- name: QueryCategoryMappings :many
SELECT cm.id, cm.merchant_pattern, c.slug AS category_slug, c.name AS category_name, cm.created_at
FROM category_mapping cm
JOIN categories c ON c.id = cm.category_id
ORDER BY cm.merchant_pattern
`

type QueryCategoryMappingsRow struct {
	ID              uuid.UUID `json:"id"`
	MerchantPattern string    `json:"merchant_pattern"`
	CategorySlug    string    `json:"category_slug"`
	CategoryName    string    `json:"category_name"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) QueryCategoryMappings(ctx context.Context) ([]QueryCategoryMappingsRow, error) {
	rows, err := q.db.QueryContext(ctx, queryCategoryMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryCategoryMappingsRow
	for rows.Next() {
		var i QueryCategoryMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantPattern,
			&i.CategorySlug,
			&i.CategoryName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryTransactionsByCardAndMonth = `-- name: QueryTransactionsByCardAndMonth :many
SELECT t.id, t.statement_id, t.card_id, t.txn_date, t.merchant_raw, t.merchant, t.amount,
       c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
       t.created_at
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.card_id = $1
  AND t.txn_date >= make_date($2::int, $3::int, 1)
  AND t.txn_date < make_date($2::int, $3::int, 1) + INTERVAL '1 month'
ORDER BY t.txn_date
`

type QueryTransactionsByCardAndMonthParams struct {
	CardID  uuid.UUID `json:"card_id"`
	Column2 int32     `json:"column_2"`
	Column3 int32     `json:"column_3"`
}

type QueryTransactionsByCardAndMonthRow struct {
	ID           uuid.UUID `json:"id"`
	StatementID  uuid.UUID `json:"statement_id"`
	CardID       uuid.UUID `json:"card_id"`
	TxnDate      time.Time `json:"txn_date"`
	MerchantRaw  string    `json:"merchant_raw"`
	Merchant     string    `json:"merchant"`
	Amount       string    `json:"amount"`
	CategoryID   uuid.UUID `json:"category_id"`
	CategoryName string    `json:"category_name"`
	CategorySlug string    `json:"category_slug"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) QueryTransactionsByCardAndMonth(ctx context.Context, arg QueryTransactionsByCardAndMonthParams) ([]QueryTransactionsByCardAndMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, queryTransactionsByCardAndMonth, arg.CardID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryTransactionsByCardAndMonthRow
	for rows.Next() {
		var i QueryTransactionsByCardAndMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.StatementID,
			&i.CardID,
			&i.TxnDate,
			&i.MerchantRaw,
			&i.Merchant,
			&i.Amount,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryTransactionsByStatement = `-- name: QueryTransactionsByStatement :many
SELECT t.id, t.statement_id, t.card_id, t.txn_date, t.merchant_raw, t.merchant, t.amount,
       c.id AS category_id, c.name AS category_name, c.slug AS category_slug,
       t.created_at
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.statement_id = $1
ORDER BY t.txn_date
`

type QueryTransactionsByStatementRow struct {
	ID           uuid.UUID `json:"id"`
	StatementID  uuid.UUID `json:"statement_id"`
	CardID       uuid.UUID `json:"card_id"`
	TxnDate      time.Time `json:"txn_date"`
	MerchantRaw  string    `json:"merchant_raw"`
	Merchant     string    `json:"merchant"`
	Amount       string    `json:"amount"`
	CategoryID   uuid.UUID `json:"category_id"`
	CategoryName string    `json:"category_name"`
	CategorySlug string    `json:"category_slug"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) QueryTransactionsByStatement(ctx context.Context, statementID uuid.UUID) ([]QueryTransactionsByStatementRow, error) {
	rows, err := q.db.QueryContext(ctx, queryTransactionsByStatement, statementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryTransactionsByStatementRow
	for rows.Next() {
		var i QueryTransactionsByStatementRow
		if err := rows.Scan(
			&i.ID,
			&i.StatementID,
			&i.CardID,
			&i.TxnDate,
			&i.MerchantRaw,
			&i.Merchant,
			&i.Amount,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
