// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bank struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	LogoUrl   sql.NullString `json:"logo_url"`
	CreatedAt time.Time      `json:"created_at"`
}

type Card struct {
	ID        uuid.UUID `json:"id"`
	BankID    uuid.UUID `json:"bank_id"`
	Label     string    `json:"label"`
	Purpose   string    `json:"purpose"`
	Last4     string    `json:"last4"`
	CreatedAt time.Time `json:"created_at"`
}
