// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const bankExists = `-- name: BankExists :one
SELECT EXISTS(SELECT 1 FROM banks WHERE id = $1)
`

func (q *Queries) BankExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, bankExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCardByID = `-- name: GetCardByID :one
SELECT c.id, c.bank_id,
       b.name AS bank_name, b.slug AS bank_slug, b.logo_url AS bank_logo_url, b.created_at AS bank_created_at,
       c.label, c.purpose, c.last4, c.created_at
FROM cards c
JOIN banks b ON b.id = c.bank_id
WHERE c.id = $1
`

type GetCardByIDRow struct {
	ID            uuid.UUID      `json:"id"`
	BankID        uuid.UUID      `json:"bank_id"`
	BankName      string         `json:"bank_name"`
	BankSlug      string         `json:"bank_slug"`
	BankLogoUrl   sql.NullString `json:"bank_logo_url"`
	BankCreatedAt time.Time      `json:"bank_created_at"`
	Label         string         `json:"label"`
	Purpose       string         `json:"purpose"`
	Last4         string         `json:"last4"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) GetCardByID(ctx context.Context, id uuid.UUID) (GetCardByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCardByID, id)
	var i GetCardByIDRow
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.BankName,
		&i.BankSlug,
		&i.BankLogoUrl,
		&i.BankCreatedAt,
		&i.Label,
		&i.Purpose,
		&i.Last4,
		&i.CreatedAt,
	)
	return i, err
}

const getCardByLast4 = `-- name: GetCardByLast4 :one
SELECT c.id, c.bank_id,
       b.name AS bank_name, b.slug AS bank_slug, b.logo_url AS bank_logo_url, b.created_at AS bank_created_at,
       c.label, c.purpose, c.last4, c.created_at
FROM cards c
JOIN banks b ON b.id = c.bank_id
WHERE c.last4 = $1
LIMIT 1
`

type GetCardByLast4Row struct {
	ID            uuid.UUID      `json:"id"`
	BankID        uuid.UUID      `json:"bank_id"`
	BankName      string         `json:"bank_name"`
	BankSlug      string         `json:"bank_slug"`
	BankLogoUrl   sql.NullString `json:"bank_logo_url"`
	BankCreatedAt time.Time      `json:"bank_created_at"`
	Label         string         `json:"label"`
	Purpose       string         `json:"purpose"`
	Last4         string         `json:"last4"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) GetCardByLast4(ctx context.Context, last4 string) (GetCardByLast4Row, error) {
	row := q.db.QueryRowContext(ctx, getCardByLast4, last4)
	var i GetCardByLast4Row
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.BankName,
		&i.BankSlug,
		&i.BankLogoUrl,
		&i.BankCreatedAt,
		&i.Label,
		&i.Purpose,
		&i.Last4,
		&i.CreatedAt,
	)
	return i, err
}

const getCardByLast4AndBank = `-- name: GetCardByLast4AndBank :one
SELECT c.id, c.bank_id,
       b.name AS bank_name, b.slug AS bank_slug, b.logo_url AS bank_logo_url, b.created_at AS bank_created_at,
       c.label, c.purpose, c.last4, c.created_at
FROM cards c
JOIN banks b ON b.id = c.bank_id
WHERE c.last4 = $1
  AND b.slug  = $2
LIMIT 1
`

type GetCardByLast4AndBankParams struct {
	Last4 string `json:"last4"`
	Slug  string `json:"slug"`
}

type GetCardByLast4AndBankRow struct {
	ID            uuid.UUID      `json:"id"`
	BankID        uuid.UUID      `json:"bank_id"`
	BankName      string         `json:"bank_name"`
	BankSlug      string         `json:"bank_slug"`
	BankLogoUrl   sql.NullString `json:"bank_logo_url"`
	BankCreatedAt time.Time      `json:"bank_created_at"`
	Label         string         `json:"label"`
	Purpose       string         `json:"purpose"`
	Last4         string         `json:"last4"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) GetCardByLast4AndBank(ctx context.Context, arg GetCardByLast4AndBankParams) (GetCardByLast4AndBankRow, error) {
	row := q.db.QueryRowContext(ctx, getCardByLast4AndBank, arg.Last4, arg.Slug)
	var i GetCardByLast4AndBankRow
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.BankName,
		&i.BankSlug,
		&i.BankLogoUrl,
		&i.BankCreatedAt,
		&i.Label,
		&i.Purpose,
		&i.Last4,
		&i.CreatedAt,
	)
	return i, err
}

const insertCard = `-- name: InsertCard :one
INSERT INTO cards (bank_id, label, purpose, last4)
VALUES ($1, $2, $3, $4)
RETURNING id, bank_id, label, purpose, last4, created_at
`

type InsertCardParams struct {
	BankID  uuid.UUID `json:"bank_id"`
	Label   string    `json:"label"`
	Purpose string    `json:"purpose"`
	Last4   string    `json:"last4"`
}

func (q *Queries) InsertCard(ctx context.Context, arg InsertCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, insertCard,
		arg.BankID,
		arg.Label,
		arg.Purpose,
		arg.Last4,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Label,
		&i.Purpose,
		&i.Last4,
		&i.CreatedAt,
	)
	return i, err
}

const queryBanks = `-- name: QueryBanks :many
SELECT id, name, slug, logo_url, created_at FROM banks ORDER BY name
`

func (q *Queries) QueryBanks(ctx context.Context) ([]Bank, error) {
	rows, err := q.db.QueryContext(ctx, queryBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bank
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryCards = `-- name: QueryCards :many
SELECT c.id, c.bank_id,
       b.name AS bank_name, b.slug AS bank_slug, b.logo_url AS bank_logo_url, b.created_at AS bank_created_at,
       c.label, c.purpose, c.last4, c.created_at
FROM cards c
JOIN banks b ON b.id = c.bank_id
ORDER BY c.created_at
`

type QueryCardsRow struct {
	ID            uuid.UUID      `json:"id"`
	BankID        uuid.UUID      `json:"bank_id"`
	BankName      string         `json:"bank_name"`
	BankSlug      string         `json:"bank_slug"`
	BankLogoUrl   sql.NullString `json:"bank_logo_url"`
	BankCreatedAt time.Time      `json:"bank_created_at"`
	Label         string         `json:"label"`
	Purpose       string         `json:"purpose"`
	Last4         string         `json:"last4"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) QueryCards(ctx context.Context) ([]QueryCardsRow, error) {
	rows, err := q.db.QueryContext(ctx, queryCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryCardsRow
	for rows.Next() {
		var i QueryCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.BankName,
			&i.BankSlug,
			&i.BankLogoUrl,
			&i.BankCreatedAt,
			&i.Label,
			&i.Purpose,
			&i.Last4,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBank = `-- name: UpsertBank :one
INSERT INTO banks (name, slug, logo_url)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE
    SET name     = EXCLUDED.name,
        logo_url = EXCLUDED.logo_url
RETURNING id, name, slug, logo_url, created_at
`

type UpsertBankParams struct {
	Name    string         `json:"name"`
	Slug    string         `json:"slug"`
	LogoUrl sql.NullString `json:"logo_url"`
}

func (q *Queries) UpsertBank(ctx context.Context, arg UpsertBankParams) (Bank, error) {
	row := q.db.QueryRowContext(ctx, upsertBank, arg.Name, arg.Slug, arg.LogoUrl)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.CreatedAt,
	)
	return i, err
}
